#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'ruby_build', :git => 'git://github.com/fnichol/chef-ruby_build.git'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv'
cookbook 'unicorn'
cookbook 'nginx'
cookbook 'postgresql'
